### ISSUE TITLE
Speech recognition not working

### ISSUE THREAD

**Issue by JoelTech43** [umangahuja1/Youtube#21]
Hi,
Love the channel but when I run the speech to text code, I get an error:

Traceback (most recent call last):
  File "C:\Users\joelh\AppData\Local\Programs\Python\Python38-32\lib\site-packages\speech_recognition\__init__.py", line 108, in get_pyaudio
    import pyaudio
ModuleNotFoundError: No module named 'pyaudio'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/joelh/OneDrive/Documents/Home/coding/Python (IDLE)/codes/Weather recording/speech.py", line 4, in <module>
    with sr.Microphone() as source:
  File "C:\Users\joelh\AppData\Local\Programs\Python\Python38-32\lib\site-packages\speech_recognition\__init__.py", line 79, in __init__
    self.pyaudio_module = self.get_pyaudio()
  File "C:\Users\joelh\AppData\Local\Programs\Python\Python38-32\lib\site-packages\speech_recognition\__init__.py", line 110, in get_pyaudio
    raise AttributeError("Could not find PyAudio; check installation")
AttributeError: Could not find PyAudio; check installation

I don't know why this is happening but when I tried to do pip install pyaudio it said something about needing visual studio C++! Do I need to do this or is there another thing I am doing wrong?

Many Regards,

Coding-Mole

**Comment by UshnishG** [comment]
Yes.... C++ needs to be installed

**Comment by 24shreya** [comment]
I was having the same problem. Then afterwards I installed a python extension in my Visual Studio Code called 'Python (IntelliSense (Pylance), Linting, Debugging (multi-threaded, remote), Jupyter Notebooks, code formatting, refactoring, unit tests, and more)'. 
The problem somehow got resolved.
@Coding-Mole

**Comment by ghost** [comment]
Or else, you can install PyAudio in Python itself.
I did it by using the pipwin module to install PyAudio.
To install PyAudio, follow these steps in either of powershell or command prompt :`

- Step 1 : `pip install pipwin`
- Step 2 : `pipwin install pyaudio`

And you'd be good to go @Coding-Mole .
