### ISSUE TITLE
I have an error while compiling this code on pycharm ,kindly help me to resolve these errors

### ISSUE THREAD

**Issue by zehrashumail** [umangahuja1/Youtube#8]
Traceback (most recent call last):
  File "C:/Users/Taqi Jaffery/PycharmProjects/openweather/longitudelatitude.py", line 55, in <module>
    main()
  File "C:/Users/Taqi Jaffery/PycharmProjects/openweather/longitudelatitude.py", line 49, in main
    by_city()
  File "C:/Users/Taqi Jaffery/PycharmProjects/openweather/longitudelatitude.py", line 11, in by_city
    show_data(data)
  File "C:/Users/Taqi Jaffery/PycharmProjects/openweather/longitudelatitude.py", line 29, in show_data
    temp = data['main']['temp']
KeyError: 'main'

**Comment by umangahuja1** [comment]
Maybe the website structure has changed. You can follow the video to learn the steps and do the necessary changes as directed in the video.
